name: "On-Screen Keyboard"
version: "1.0.0"
slug: "onscreen-keyboard"
description: "A smooth, animated on-screen keyboard for Home Assistant dashboards"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
panel_icon: "mdi:keyboard"
startup: application
boot: auto
ports:
  8123/tcp: 8123
webui: "http://[HOST]:[PORT:8123]"
options:
  theme: "light"
  animation_speed: 300
  keyboard_layout: "qwerty"
schema:
  theme:
    name: "Theme"
    description: "Choose between light and dark theme"
    required: true
    default: "light"
    type: select
    options:
      - light
      - dark
  animation_speed:
    name: "Animation Speed"
    description: "Speed of the slide animation in milliseconds"
    required: true
    default: 300
    type: integer
  keyboard_layout:
    name: "Keyboard Layout"
    description: "Select your preferred keyboard layout"
    required: true
    default: "qwerty"
    type: select
    options:
      - qwerty
      - azerty
      - qwertz 